CREATE DATABASE IF NOT EXISTS zoo;
USE zoo;

CREATE TABLE IF NOT EXISTS animais (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    especie VARCHAR(100) NOT NULL,
    idade INT NOT NULL,
    habitat VARCHAR(100) NOT NULL
);
